#  Adapted from https://kodimensional.dev/posts/2019-02-25-haskell-travis

sudo: true
language: haskell

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  - ghc: 8.6.5
  - ghc: 8.8.3
  - ghc: 8.10.3

  # Stack
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh
      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      # cabal new-test --enable-tests
      true
    else
      stack test
    fi

