on: [push]
name: build
jobs:
  cabal:
    strategy:
      matrix:
        host: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.host }}
    name: Stack on ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v6
      - uses: haskell-actions/setup@v2
      - run: cabal build all
      - run: cabal test all --test-show-details=streaming

