on: [push]
name: build
jobs:
  cabal:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        ghc: ['9.0', '9.4', '9.6', '9.8', '9.10', 'latest']
    name: GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v4
      - name: Install PCRE.
        run: sudo apt-get install -y pcre2-utils
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal build
  stack:
    runs-on: 'ubuntu-latest'
    name: Stack
    steps:
      - uses: actions/checkout@v4
      - name: Install PCRE.
        run: sudo apt-get install -y pcre2-utils
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
      - run: stack build

